<?php

function stdh_form_alter(&$form, &$form_state, $form_id) {
//print_r($form['#id']);
//   print '<pre>';
//  print_r($form);
//  print '</pre>';
    $pos = strpos($form_id, "webform_client_form");
  if ($pos !== FALSE) {
    foreach (element_children($form['submitted']) as $element) {
      if (isset($form['submitted'][$element]['#title']))
        $form['submitted'][$element]['#title'] = t($form['submitted'][$element]['#title']);
    }
    if (isset($form['title']['#title'])) {
      $form['title']['#title'] = t($form['title']['#title']);
    }
    
}

 if (isset($form['#node']->type) && ($form['#node']->type == 'webform')) {
if ($form['#id']== 'webform-client-form-64'){
     //print_r($form);
    foreach ($form["submitted"] as $key => $value) {
      switch ($value["#type"]) {
        case 'textfield':
        case 'textarea':
        case 'webform_email':
          $form["submitted"][$key]['#attributes']["placeholder"] = $value["#title"];
          break;
      } 
    }
  }
}
 //break;

     if ($form['#id']== 'user_login'){
     //print_r($form);
    $form['name']['#description']="";
      $form['pass']['#description']="";
      $items = array();
      $items[] = l(t('Request new password'), 'user/password', 
              array('attributes' => array('title' => t('Request new password via e-mail.'))));
      $form['links'] = array('#markup' => theme('item_list', array('items' => $items)), '#weight' => 200);
      }

  if ($form['#id']== 'user-profile-form'){

  }
}


function stdh_form_user_register_form_alter(&$form, &$form_state, $form_id) {
 
  $form['#theme'] = 'user_register';
  $form['actions']['submit']['#value'] = t('REGISTER');
  $form['account']['mail']['#title'] = t('E-mail');
  
  
}
function stdh_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
      print '<pre>';
  print_r($form);
  print '</pre>';
  $form['account']['locale']['#access'] =0;
 
}


   ?>

