<?php

/**
 * 
 * Implementation of hook_menu
 */
function bilbaal_registration_menu() {
  $items = array();
  $items['bilbaal/register/organization'] = array(
    'title' => t('REGISTRATION - Organization'),
    'description' => t('User Registration'),
    'page callback' => '_bilbaal_register_organization',
    'access callback' => 'bilbaal_registration_access',
  );
  $items['bilbaal/register/member'] = array(
    'title' => t('REGISTRATION - Individual'),
    'description' => t('User Registration'),
    'page callback' => '_bilbaal_register_member',
    'access callback' => 'bilbaal_registration_access',
  );
  $items['bilbaal/register/success'] = array(
    'title' => t('REGISTRATION - Organization'),
    'description' => t('User Registration'),
    'page callback' => '_bilbaal_register_success',
    'access callback' => 'bilbaal_registration_access',
  );
  return $items;
}

/**
 * 
 * Menu Call back bilbaal/register/organiztion.
 */
function _bilbaal_register_organization() {
  $output = '';
  drupal_add_css(drupal_get_path('module', 'bilbaal_registration') . '/css/bilbaal_registration.css');
  drupal_add_js(drupal_get_path('module', 'bilbaal_registration') . '/js/bilbaal_registration.js');
  $output .= render(drupal_get_form('bilbaal_organization_registration_form'));
  return $output;
}

/**
 * 
 * Menu Call back bilbaal/register/member
 */
function _bilbaal_register_member() {
  $output = '';
  drupal_add_css(drupal_get_path('module', 'bilbaal_registration') . '/css/bilbaal_registration.css');
  drupal_add_js(drupal_get_path('module', 'bilbaal_registration') . '/js/bilbaal_registration.js');
  $output .= render(drupal_get_form('bilbaal_member_registration_form'));
  return $output;
}

/**
 * 
 * Implementation of hook_form
 */
function bilbaal_member_registration_form($form, $form_state) {
  if (!isset($form_state['stage'])) $form_state['stage'] = 'account';
  $form = array('#attributes' => array('class' => array('registration-form')));
  $form = _member_registration_get_header($form, $form_state);
  
  switch ($form_state['stage']){
    case 'account':
      $form['registration_steps'] = array('#markup' => '<div class="registration-steps account"></div>');
      return _registration_account_form($form, $form_state);
      break;
    case 'detailed':
      $form['registration_steps'] = array('#markup' => '<div class="registration-steps detailed"></div>');
      return _member_registration_detailed_form($form, $form_state);
      break;
  }
}

function bilbaal_member_registration_form_validate($form, &$form_state) {
  if ($form_state['triggering_element']['#value'] == t('Back')) {
    return;
  }
  if ($form_state['triggering_element']['#value'] == t('Cancel')) {
    drupal_goto('<front>');
  }
  
  switch ($form_state['stage']) {
    case 'account':
      if (!filter_var($form_state['values']['email'], FILTER_VALIDATE_EMAIL)) {
        form_set_error('email', t('Please enter a valid email address.'));
      }
      else{
        if ($user = user_load_by_name($form_state['values']['email'])) {
          form_set_error('email', t('Email is already registered.'));
        }
      }
      if ($form_state['values']['password'] != $form_state['values']['re_password']) {
        form_set_error('password', t('Password does not match.'));
      }
      break;
    
    case 'detailed':
      if(!empty($_FILES['files']['name']['logo'])){
        $types = array('image/gif', 'image/jpeg', 'image/png');
        if(!in_array($_FILES['files']['type']['logo'], $types)){
          form_set_error('logo', t('Profile Picture type mismatch.'));
        }
      } 
      break;
  }
}

function bilbaal_member_registration_form_submit($form, &$form_state) {
  global $language;
  switch ($form_state['stage']) {
    case 'account':
      $form_state['steps']['account'] = $form_state['values'];
      if ($form_state['triggering_element']['#value'] == t('Next')){
        $form_state['new_stage'] = 'detailed';
      }
     break;
     
    case 'detailed':
      $form_state['steps']['detailed'] = $form_state['values'];
      if ($form_state['triggering_element']['#value'] == t('Register')) {
        $account = $form_state['steps']['account'];
        $detailed = $form_state['steps']['detailed'];

        $new_user = array(
          'name' => $account['email'],
          'pass' => $account['password'],
          'mail' => $account['email'],
          'status' => 1, // status active
          'init' => $account['email'],
          'roles' => array(2 => 'authenticated user', 5 => 'member'),
          'language' => $language->language,
        );

        $user = user_save(null, $new_user); // create new user
        $profile = profile_create(array('type' => 'member', 'uid' => $user->uid));
        $lang = LANGUAGE_NONE;
        $profile->field_user_name[$lang][0]['value'] = $detailed['name'];
        $profile->field_user_sname[$lang][0]['value'] = $detailed['sname'];
        $profile->field_user_location[$lang][0]['value'] = $detailed['country'];
        $profile->field_user_year[$lang]['0']['value'] = $detailed['birth'];
        $profile->field_user_city[$lang]['0']['value'] = $detailed['city'];
        $profile->field_user_village[$lang]['0']['tid'] = $detailed['village'];

        // get selected areas
        $areas = array();
        foreach ($detailed['area'] as $key => $value) {
          if ($value != 0) {
            $areas[]['tid'] = $value;
          }
        }
        $profile->field_user_areas[$lang] = $areas;

        // get selected skills
        $skills = array();
        foreach ($detailed['offer'] as $key => $value) {
          if ($value != 0) {
            $skills[]['tid'] = $value;
          }
        }
        $profile->field_member_skills[$lang] = $skills;

        // get selected serves
        $serves = array();
        foreach ($detailed['support'] as $key => $value) {
          if ($value != 0) {
            $serves[]['tid'] = $value;
          }
        }
        $profile->field_member_serve[$lang] = $serves;

        // profile picture
        if(!empty($_FILES['files']['name']['logo'])){
          $picture = file_save_upload('logo', array(), 'public://pictures');
          $picture->uid = $user->uid;
          $picture = file_save($picture);
          $profile->field_user_picture[$lang][0] = (array) $picture;
        }
        else{
          $handle = fopen(drupal_get_path('theme', 'bilbaal') . '/images/individual.png', 'r');
          $picture = file_save_data($handle, 'public://pictures');
          fclose($handle);
          $picture->uid = $user->uid;
          $picture->filename = $picture->filename . '.png';
          $picture = file_save($picture);
          $profile->field_user_picture[$lang][0] = (array) $picture;
        }

        $form_state = array();
        $form_state['values'] = array();
        $form_state['values']['profile_member'] = array();
        $form = array();
        $form['#parents'] = array();
        field_attach_submit('profile2', $profile, $form, $form_state); // attach $profile to profile2 submit
        $profile->bundle = 'member'; // main is the profile type which is created in step 3
        profile2_save($profile);

        // Send notification email
        bilbaal_emails_send_email('confirmation_individual', array('receiver' => $user));
        //_user_mail_notify('register_no_approval_required', $user);
        drupal_goto('bilbaal/register/success');
      }
      else{
        $form_state['new_stage'] = 'account';
      }
    break;
  }
  
  if (isset($form_state['steps']['form_build_id'])) {
    $form_state['values']['form_build_id'] = $form_state['steps']['form_build_id'];
  }
  $form_state['steps']['form_build_id'] = $form_state['values']['form_build_id'];
  $form_state['stage'] = $form_state['new_stage'];
  $form_state['rebuild'] = TRUE;
}

function _member_registration_get_header($form, &$form_state) {
  $form_state['stage'] = isset($form_state['stage']) ? $form_state['stage'] : 1; 
  $form_stages = array('account' => 1, 'detailed' => 2);
  if (isset($form_stages[$form_state['stage']])) {
   $current_step = $form_stages[$form_state['stage']];
  }
  else {
   $current_step = 1;
  }
   
  $stages = array(
    1 => array('data' => t('Email and Password')),
    2 => array('data' => t('Detailed Information')),
  );
   
  $stages[$current_step]['class'] = array('active');
  $stages_list = theme('item_list', array('items' => $stages, 'attributes' => array('class' => array('registration-header'))));
  $mandatory_text = '<div class="messages--status messages status">'.
                                      t('All fields are required except for the Profile Picture.').
                                   '</div>';
  $form['header'] = array('#markup' => $stages_list . $mandatory_text, '#weight' => -2);
  return $form;
}

function _member_registration_detailed_form($form, &$form_state){
  $values = isset($form_state['steps']['detailed']) ? $form_state['steps']['detailed'] : array();
  
  $form['detailed']['logo'] = array(
    '#type' => 'file',
    '#title' => t('Profile Picture'),
    '#description' => t('Only JPEG, GIF, and PNG files accepted'),
    '#size' => 22,
    '#field_prefix' => '<span class="logo-demo"></span>',
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  $form['detailed']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#maxlength' => 60,
    '#default_value' => isset($values['name']) ? $values['name'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
  );
  $form['detailed']['sname'] = array(
    '#type' => 'textfield',
    '#title' => t('Second name'),
    '#maxlength' => 60,
    '#default_value' => isset($values['sname']) ? $values['sname'] : NULL,
    '#required' => TRUE,
    '#suffix' => '</div>',
  );
  $form['detailed']['country'] = array(
    '#type' => 'select',
    '#title' => t('Location'),
    '#options' => array('' => t('Choose Country')) + list_predefined_options_list_option_countries(),
//    '#description' => t('Choose country of operation'),
    '#default_value' => isset($values['country']) ? $values['country'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
  );
  $form['detailed']['city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#default_value' => isset($values['city']) ? $values['city'] : NULL,
    '#required' => TRUE,
    '#suffix' => '</div>',
  );
  $form['detailed']['village'] = array(
    '#type' => 'select',
    '#title' => t('If you identify as Palestinian, where are you originally from?'),
    '#options' => array_merge(array('' => t('- None -')), get_taxonomy_options(8, FALSE)),
//    '#description' => t('If you identify as Palestinian, where are you originally from?'),
    '#default_value' => isset($values['village']) ? $values['village'] : NULL,
    '#prefix' => '<div class="row clearfix">',
  );
  $years = array();
  for($i=1900; $i<=intval(date('Y')); $i++){
    $years[$i] = $i;
  }
  $form['detailed']['birth'] = array(
    '#type' => 'select',
    '#title' => t('Year of birth'),
    '#options' => $years,
//    '#description' => t('Year'),
    '#default_value' => isset($values['birth']) ? $values['birth'] : NULL,
    '#required' => TRUE,
    '#suffix' => '</div>',
  );
  $form['detailed']['area'] = array(
    '#type' => 'checkboxes',
    '#title' => t('What subjects interest you?'),
    '#options' => get_taxonomy_options(5, FALSE),
//    '#default_value' => isset($values['area']) ? $values['area'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  $form['detailed']['offer'] = array(
    '#type' => 'checkboxes',
    '#title' => t('What skill set can you offer?'),
    '#options' => get_taxonomy_options(6, FALSE),
//    '#default_value' => isset($values['offer']) ? $values['offer'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  $form['detailed']['support'] = array(
    '#type' => 'checkboxes',
    '#title' => t('How would you like to serve?'),
    '#options' => get_taxonomy_options(7, FALSE),
//    '#default_value' => isset($values['support']) ? $values['support'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  
  $form['back'] = array('#type' => 'submit', '#value' => t('Back'), '#attributes' => array('class' => array('cancel')),
                                      '#limit_validation_errors' => array(), '#submit' => array(), '#prefix' => '<div class="row clearfix">',);
  $form['register'] = array('#type' => 'submit', '#value' => t('Register'), '#suffix' => '</div>',);
  
  return $form;
}

/**
 * 
 * Implementation of hook_form
 */
function bilbaal_organization_registration_form($form, &$form_state) {
  if (!isset($form_state['stage'])) $form_state['stage'] = 'account';
  $form = array('#attributes' => array('class' => array('registration-form')));
  $form = _organization_registration_get_header($form, $form_state);
  
  switch ($form_state['stage']){
    case 'account':
      $form['registration_steps'] = array('#markup' => '<div class="registration-steps account"></div>');
      return _registration_account_form($form, $form_state);
      break;
    case 'basic':
      $form['registration_steps'] = array('#markup' => '<div class="registration-steps basic"></div>');
      return _organization_registration_basic_form($form, $form_state);
      break;
    case 'detailed':
      $form['registration_steps'] = array('#markup' => '<div class="registration-steps detailed"></div>');
      return _organization_registration_detailed_form($form, $form_state);
      break;
  }
}

function bilbaal_organization_registration_form_validate($form, &$form_state) {
  if ($form_state['triggering_element']['#value'] == t('Back')) {
    return;
  }
  if ($form_state['triggering_element']['#value'] == t('Cancel')) {
    drupal_goto('<front>');
  }
  
  switch ($form_state['stage']) {
    case 'account':
      if (!filter_var($form_state['values']['email'], FILTER_VALIDATE_EMAIL)) {
        form_set_error('email', t('Please enter a valid email address.'));
      }
      else{
        if ($user = user_load_by_name($form_state['values']['email'])) {
          form_set_error('email', t('Email is already registered.'));
        }
      }
      if ($form_state['values']['password'] != $form_state['values']['re_password']) {
        form_set_error('password', t('Password does not match.'));
      }
      break;
    
    case 'basic':
      if(!empty($_FILES['files']['name']['logo'])){
        $types = array('image/gif', 'image/jpeg', 'image/png');
        if(!in_array($_FILES['files']['type']['logo'], $types)){
          form_set_error('logo', t('Organization logo type mismatch.'));
        }
      }
      if (!empty($form_state['values']['inquires']) && !filter_var($form_state['values']['inquires'], FILTER_VALIDATE_EMAIL)) {
        form_set_error('inquires', t('Please insert a valid inquries email.'));
      }
      if (!empty($form_state['values']['website'])) {
        if (strpos($form_state['values']['website'], 'http://') !== 0) {
          $form_state['values']['website'] = 'http://' . $form_state['values']['website'];
        }
      }
      if (!empty($form_state['values']['website']) && !filter_var($form_state['values']['website'], FILTER_VALIDATE_URL)) {
        form_set_error('website', t('Please insert a valid website.'));
        $errors = true;
      }      
      break;
    
    case 'detailed':
      
      break;
  }
}

function bilbaal_organization_registration_form_submit($form, &$form_state) {
  global $language;
  switch ($form_state['stage']) {
    case 'account':
      $form_state['steps']['account'] = $form_state['values'];
      if ($form_state['triggering_element']['#value'] == t('Next')){
        $form_state['new_stage'] = 'basic';
      }
     break;
     
    case 'basic':
      $form_state['steps']['basic'] = $form_state['values'];
      if ($form_state['triggering_element']['#value'] == t('Next')){
        if(!empty($_FILES['name']['logo'])){
          $picture = file_save_upload('logo', array(), 'public://organizations');
          $form_state['steps']['basic']['logo'] = $picture;
        }
        $form_state['new_stage'] = 'detailed';
      }
      else{
        $form_state['new_stage'] = 'account';
      }
      break;
      
    case 'detailed':
      $form_state['steps']['detailed'] = $form_state['values'];
      if ($form_state['triggering_element']['#value'] == t('Register')) {
        $account = $form_state['steps']['account'];
        $basic = $form_state['steps']['basic'];
        $detailed = $form_state['steps']['detailed'];
        $new_user = array(
          'name' => $account['email'],
          'pass' => $account['password'],
          'mail' => $account['email'],
          'status' => 0, // status active
          'init' => $account['email'],
          'roles' => array(2 => 'authenticated user', 4 => 'organization'),
          'language' => $language->language,
        );

        $user = user_save(null, $new_user); // create new user
        $profile = profile_create(array('type' => 'organization', 'uid' => $user->uid));
        $lang = LANGUAGE_NONE;
        $profile->field_user_name[$lang][0]['value'] = $basic['name'];
        $profile->field_user_location[$lang][0]['value'] = $basic['country'];
        $profile->field_user_year[$lang]['0']['value'] = $basic['founded'];
        $profile->field_user_fax[$lang]['0']['value'] = $basic['fax'];
        $profile->field_organization_telephone[$lang]['0']['value'] = $basic['telephone'];
        $profile->field_user_city[$lang]['0']['value'] = $basic['city'];
        $profile->field_organization_street[$lang]['0']['value'] = $basic['street'];
        $profile->field_organization_inquiries[$lang]['0']['value'] = $basic['inquires'];
        $profile->field_organization_website[$lang]['0']['value'] = $basic['website'];
        $profile->field_user_description[$lang]['0']['value'] = $detailed['background'];

        // get selected areas
        $areas = array();
        foreach ($detailed['area'] as $key => $value) {
          if ($value != 0) {
            $areas[]['tid'] = $value;
          }
        }
        $profile->field_user_areas[$lang] = $areas;

        // get selected skills
        $kinds = array();
        foreach ($basic['kind'] as $key => $value) {
          if ($value != 0) {
            $kinds[]['tid'] = $value;
          }
        }
        $profile->field_organization_type[$lang] = $kinds;

        // get selected serves
        $serves = array();
        foreach ($detailed['support'] as $key => $value) {
          if ($value != 0) {
            $serves[]['tid'] = $value;
          }
        }
        $profile->field_user_serve[$lang] = $serves;

        // profile picture
        if(!empty($basic['logo'])){
          $picture = $basic['logo'];
          $picture->uid = $user->uid;
          $picture = file_save($picture);
          $profile->field_user_picture[$lang][0] = (array) $picture;
        }
        else{
          $handle = fopen(drupal_get_path('theme', 'bilbaal') . '/images/organization.png', 'r');
          $picture = file_save_data($handle, 'public://pictures');
          fclose($handle);
          $picture->uid = $user->uid;
          $picture->filename = $picture->filename . '.png';
          $picture = file_save($picture);
          $profile->field_user_picture[$lang][0] = (array) $picture;
        }

        $form_state = array();
        $form_state['values'] = array();
        $form_state['values']['profile_organization'] = array();
        $form = array();
        $form['#parents'] = array();
        field_attach_submit('profile2', $profile, $form, $form_state); // attach $profile to profile2 submit
        $profile->bundle = 'organization'; // main is the profile type which is created in step 3
        profile2_save($profile);

        // Send notification email
        bilbaal_emails_send_email('confirmation_organization', array('receiver' => $user));
        //_user_mail_notify('register_pending_approval_admin', $user);
        drupal_goto('bilbaal/register/success');
      }
      else{
        $form_state['new_stage'] = 'basic';
      }
     break;
  }
   
  if (isset($form_state['steps']['form_build_id'])) {
    $form_state['values']['form_build_id'] = $form_state['steps']['form_build_id'];
  }
  $form_state['steps']['form_build_id'] = $form_state['values']['form_build_id'];
  $form_state['stage'] = $form_state['new_stage'];
  $form_state['rebuild'] = TRUE;
}

function _organization_registration_get_header($form, &$form_state) {
  $form_state['stage'] = isset($form_state['stage']) ? $form_state['stage'] : 1; 
  $form_stages = array('account' => 1, 'basic' => 2, 'detailed' => 3);
  if (isset($form_stages[$form_state['stage']])) {
   $current_step = $form_stages[$form_state['stage']];
  }
  else {
   $current_step = 1;
  }
   
  $stages = array(
    1 => array('data' => t('Email and Password')),
    2 => array('data' => t('Basic Information')),
    3 => array('data' => t('Detailed Information')),
  );
   
  $stages[$current_step]['class'] = array('active');
  $stages_list = theme('item_list', array('items' => $stages, 'attributes' => array('class' => array('registration-header'))));
  $mandatory_text = '<div class="messages--status messages status">'.
                                      t('All fields are required except for the Logo.').
                                   '</div>';
  $form['header'] = array('#markup' => $stages_list . $mandatory_text);
  return $form;
}

function _registration_account_form($form, &$form_state) {
  $values = isset($form_state['steps']['account']) ? $form_state['steps']['account'] : array();
 
  if(arg(2) == 'member'){
    $form['account'] = array(
      '#type' => 'container',
      '#attributes' => array('class' => array('clearfix')),
      '#tree' => FALSE,
      '#weight' => -1,
    );
    
    $form['hybridauth'] = array(
      '#type' => 'hybridauth_widget',
    );
  }
  
  $form['account']['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email Address'),
    '#maxlength' => 100,
    '#description' => t('A Valid email address'),
    '#default_value' => isset($values['email']) ? $values['email'] : NULL,
    '#required' => TRUE,
    '#rules' => array('email'),
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  $form['account']['password'] = array(
    '#type' => 'password',
    '#title' => t('Password'),
    '#maxlength' => 15,
    '#description' => t('6-15 characters'),
    '#required' => TRUE,
    '#rules' => array('length[6,15]'),
    '#prefix' => '<div class="row clearfix">',
  );
  $form['account']['re_password'] = array(
    '#type' => 'password',
    '#title' => t('Repeat Password'),
    '#maxlength' => 15,
    '#required' => TRUE,
    '#rules' => array('length[6,15]', 'match_field[re_password]'),
    '#suffix' => '</div>',
  );
  $form['cancel'] = array('#type' => 'submit', '#value' => t('Cancel'), '#attributes' => array('class' => array('cancel')),
                                      '#limit_validation_errors' => array(), '#submit' => array(), '#prefix' => '<div class="row clearfix">',);
  $form['next'] = array('#type' => 'submit', '#value' => t('Next'), '#suffix' => '</div>',);
     
  return $form;
}

function _organization_registration_basic_form($form, &$form_state){
  $values = isset($form_state['steps']['basic']) ? $form_state['steps']['basic'] : array();
  
  $form['basic']['logo'] = array(
    '#type' => 'file',
    '#title' => t('Organization Logo'),
    '#description' => t('Only JPEG, GIF, and PNG files accepted'),
    '#size' => 22,
    '#field_prefix' => '<span class="logo-demo"></span>',
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  $form['basic']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Organization Name'),
    '#maxlength' => 60,
    '#description' => t('Choose your name'),
    '#default_value' => isset($values['name']) ? $values['name'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
  );
  $years = array();
  for($i=1900; $i<=intval(date('Y')); $i++){
    $years[$i] = $i;
  }
  $form['basic']['founded'] = array(
    '#type' => 'select',
    '#title' => t('When were you established?'),
    '#options' => $years,
    '#description' => t('Year'),
    '#default_value' => isset($values['founded']) ? $values['founded'] : NULL,
    '#required' => TRUE,
    '#suffix' => '</div>',
  );
  $form['basic']['kind'] = array(
    '#type' => 'checkboxes',
    '#title' => t('What type of organization are you?'),
    '#options' => get_taxonomy_options(4, FALSE),
    '#description' => t('Choose all that applies'),
//    '#default_value' => isset($values['kind']) ? $values['kind'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  $form['basic']['country'] = array(
    '#type' => 'select',
    '#title' => t('Country of operation'),
    '#options' => array('' => t('Choose Country')) + list_predefined_options_list_option_countries(),
    '#description' => t('Choose country of operation'),
    '#default_value' => isset($values['country']) ? $values['country'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
  );
  $form['basic']['city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#maxlength' => 60,
    '#description' => t('Choose city'),
    '#default_value' => isset($values['city']) ? $values['city'] : NULL,
    '#required' => TRUE,
    '#suffix' => '</div>',
  );
  $form['basic']['street'] = array(
    '#type' => 'textfield',
    '#title' => t('Street Address'),
    '#maxlength' => 60,
    '#description' => t('Organization street address'),
    '#default_value' => isset($values['street']) ? $values['street'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
  );
  $form['basic']['telephone'] = array(
    '#type' => 'textfield',
    '#title' => t('Telephone Number'),
    '#maxlength' => 60,
    '#description' => t('Office telephone number'),
    '#default_value' => isset($values['telephone']) ? $values['telephone'] : NULL,
    '#required' => TRUE,
    '#suffix' => '</div>',
  );
  $form['basic']['fax'] = array(
    '#type' => 'textfield',
    '#title' => t('Fax Number'),
    '#maxlength' => 60,
    '#description' => t('Office fax number'),
    '#default_value' => isset($values['fax']) ? $values['fax'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
  );
  $form['basic']['inquires'] = array(
    '#type' => 'textfield',
    '#title' => t('General Inquiries Email'),
    '#maxlength' => 60,
    '#description' => t('Email for inquiries'),
    '#default_value' => isset($values['inquires']) ? $values['inquires'] : NULL,
    '#required' => TRUE,
    '#rules' => array('email'),
    '#suffix' => '</div>',
  );
  $form['basic']['website'] = array(
    '#type' => 'textfield',
    '#title' => t('Website'),
    '#maxlength' => 60,
    '#description' => t('Organization website'),
    '#default_value' => isset($values['website']) ? $values['website'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  
  $form['back'] = array('#type' => 'submit', '#value' => t('Back'), '#attributes' => array('class' => array('cancel')),
                                      '#limit_validation_errors' => array(), '#submit' => array(), '#prefix' => '<div class="row clearfix">',);
  $form['next'] = array('#type' => 'submit', '#value' => t('Next'), '#suffix' => '</div>',);
  
  return $form;
}

function _organization_registration_detailed_form($form, &$form_state){
  $values = isset($form_state['steps']['detailed']) ? $form_state['steps']['detailed'] : array();
  
  $form['detailed']['background'] = array(
    '#type' => 'textarea',
    '#title' => t('Organization background and experience'),
    '#description' => t('Few paragraphes about your organization'),
//    '#default_value' => isset($values['background']) ? $values['background'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  $form['detailed']['area'] = array(
    '#type' => 'checkboxes',
    '#title' => t('What is the main focus area of yoru work?'),
    '#options' => get_taxonomy_options(5, FALSE),
    '#description' => t('Choose all that applies'),
//    '#default_value' => isset($values['area']) ? $values['area'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  $form['detailed']['support'] = array(
    '#type' => 'checkboxes',
    '#title' => t('What kind of support does your organization require ?'),
    '#options' => get_taxonomy_options(7, FALSE),
    '#description' => t('Choose all that applies'),
//    '#default_value' => isset($values['support']) ? $values['support'] : NULL,
    '#required' => TRUE,
    '#prefix' => '<div class="row clearfix">',
    '#suffix' => '</div>',
  );
  
  $form['back'] = array('#type' => 'submit', '#value' => t('Back'), '#attributes' => array('class' => array('cancel')),
                                      '#limit_validation_errors' => array(), '#submit' => array(), '#prefix' => '<div class="row clearfix">',);
  $form['register'] = array('#type' => 'submit', '#value' => t('Register'), '#suffix' => '</div>',);
  
  return $form;
}

/**
 * Access call back for registration pages
 */
function bilbaal_registration_access(){
  global $user;
  if($user->uid){
    return FALSE;
  }
  else{
    return TRUE;
  }
}

/*
 * Return success page
 */
function _bilbaal_register_success(){
  drupal_add_css(drupal_get_path('module', 'bilbaal_registration') . '/css/bilbaal_registration.css');
  $output = '<div class="registration-form">';
  $output .= '<div class="registration-steps success"></div>';
  $output .= '<ul class="registration-header"><li class="active">'.t('Success!').'</li></ul>';
  $output .= t('You have successfully completed registration. A confirmation email will be sent to you shortly.');
  $output .= '</div>';
  
  return $output;
}

/**
 * Invoked when a new user account is created through HybridAuth.
 * @param object $account
 *   User account object.
 * @param array $data
 *   HybridAuth identity data.
 */
function bilbaal_registration_hybridauth_user_insert($account, $data) {
  global $language;
  $edit = array(
    'roles' => array(2 => 'authenticated user', 5 => 'member'),
    'language' => $language->language,
  );
  user_save($account, $edit);

  $profile = profile_create(array('type' => 'member', 'uid' => $account->uid));
  $lang = LANGUAGE_NONE;
  $profile->field_user_name[$lang][0]['value'] = $data['firstName'];
  $profile->field_user_sname[$lang][0]['value'] = $data['lastName'];
  $profile->field_user_location[$lang][0]['value'] = $data['country'];
  $profile->field_user_year[$lang]['0']['value'] = $data['birthYear'];
  $profile->field_user_city[$lang]['0']['value'] = $data['city'];

  // profile picture
  if(!empty($data['photoURL'])){
    $picture = system_retrieve_file($data['photoURL'], 'public://pictures', TRUE);
    $picture->uid = $account->uid;
    $picture = file_save($picture);
    $profile->field_user_picture[$lang][0] = (array) $picture;
  }
        
  $form_state = array();
  $form_state['values'] = array();
  $form_state['values']['profile_member'] = array();
  $form = array();
  $form['#parents'] = array();
  field_attach_submit('profile2', $profile, $form, $form_state);
  $profile->bundle = 'member';
  profile2_save($profile);

  $_GET['destination'] = 'user/'.$account->uid.'/edit/member';
  //drupal_goto('user/'.$account->uid.'/edit/member');
}
